### ISSUE TITLE
Basic Machine Learning Models Suggestion

### ISSUE THREAD

**Issue by JordanMicahBennett** [datamodeja/Data-Science-Meet-Up#1]
In addition to your current schedule, perhaps it would be reasonable to add basic machine learning programming components, without helpers like numpy, sklearn, panda or tensorflow etc.

1. For example, 6 months ago in June 2019, at an event hosted by ITS 2019 at UWI Jamaica, I lead a session,  [where I taught students how to write a basic artificial neural network from scratch](https://github.com/JordanMicahBennett/Live-ITS-2019-Artificial-Neural-Network-Tutorial-Code).
2. Understanding how to write a basic artificial neural network can gain people intuition to apply libraries like tensorflow or mxnet. This could help people to better adopt data science libraries like the ones used in your python notebook.

**Comment by datamodeja** [comment]
Hi Jordan, thank you for your suggestion, that is actually in the pipeline for February or April 2020, would you like to volunteer as a presenter to share your expertise?
